FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install production dependencies only
RUN npm i --omit=dev

# Copy server files
COPY src/utils/server.js ./server.js

# Environment variables
ENV NODE_ENV=production
ENV PORT=3000

# Expose backend port
EXPOSE 3000

# Start server
CMD ["node", "server.js"] 