{{- if .Values.ui.ingress.enabled -}}
{{- $fullName := include "vaultinjector.ui.fullname" . -}}
{{- $svcPort := .Values.ui.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vaultinjector.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ui.ingress.className }}
  ingressClassName: {{ .Values.ui.ingress.className }}
  {{- end }}
  {{- if .Values.ui.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ui.ingress.host | quote }}
      secretName: .Values.ui.ingress.tls.secretName
  {{- end }}
  rules:
    - host: {{ .Values.ui.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ui.ingress.path }}
            pathType: {{ .Values.ui.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }} 